version: '3.8'

services:
  traefik:
    image: traefik:v2.11
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=teamdcrypto24@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=./acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlsChallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpChallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      #- "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik:/etc/traefik"
      - "./certs:/certs"
      - "./acme.json:/acme.json"
    networks:
      - traefik-network
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.http_catchall.entrypoints=web"
      - "traefik.http.routers.http_catchall.middlewares=secured"
      - "traefik.http.middlewares.secured.chain.middlewares=redirect"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect.redirectscheme.permanent=true"

  fastapi:
    image: zasoliton/template:latest
    networks:
      - traefik-network
      - default
    depends_on:
      - traefik
    container_name: template_fastapi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.service=template_fastapi@docker"
      - "traefik.http.routers.fastapi.rule=Host(`oms.lyqas.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.fastapi.entrypoints=web"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.template_fastapi.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-network"

networks:
  traefik-network:
    external: true
