# Traefik configuration file
api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: teamdcrypto24@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
